-- FULL SYNCED SUPABASE SCHEMA (IDEMPOTENT)
-- Standardized on 'parties' and 'lessons'

-- 1. PROFILES
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL,
  display_name TEXT,
  role TEXT DEFAULT 'participant' CHECK (role IN ('participant', 'host', 'admin', 'dj', 'instructor', 'media', 'banned', 'unassigned')),
  photo_url TEXT,
  phone TEXT,
  points INTEGER DEFAULT 0,
  rank_percentile INTEGER DEFAULT 100,
  short_bio TEXT,
  description TEXT,
  specialties TEXT,
  career TEXT,
  portfolio_url TEXT,
  portfolio_images TEXT[],
  studio_location TEXT,
  followers_count INTEGER DEFAULT 0,
  priority INTEGER DEFAULT 0,
  is_approved BOOLEAN DEFAULT false,
  preferences JSONB DEFAULT '{"genres": [], "regions": [], "roles": [], "types": [], "autoApplied": false}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1.2 SPECIALIZED
CREATE TABLE IF NOT EXISTS instructors (
  id UUID REFERENCES profiles(id) ON DELETE CASCADE PRIMARY KEY,
  specialty_genres TEXT[],
  experience_years INTEGER,
  curriculum_link TEXT,
  bio TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS djs (
  id UUID REFERENCES profiles(id) ON DELETE CASCADE PRIMARY KEY,
  music_style TEXT[],
  main_equipment TEXT,
  mixcloud_url TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS creators (
  id UUID REFERENCES profiles(id) ON DELETE CASCADE PRIMARY KEY,
  category TEXT CHECK (category IN ('photo', 'video', 'both')),
  equipment_list TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. PARTIES
CREATE TABLE IF NOT EXISTS parties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  location_name TEXT,
  formatted_address TEXT,
  city TEXT,
  country TEXT,
  lat FLOAT8,
  lng FLOAT8,
  status TEXT DEFAULT 'pending' CHECK (status IN ('draft', 'pending', 'published', 'cancelled', 'expired')),
  price INTEGER DEFAULT 0,
  max_attendees INTEGER DEFAULT 0,
  host_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  image_url TEXT,
  is_banner BOOLEAN DEFAULT false,
  priority INTEGER DEFAULT 0,
  likes_count INTEGER DEFAULT 0,
  djs TEXT[],
  performances TEXT[],
  media_experts TEXT[],
  tickets JSONB DEFAULT '[]',
  payment_method TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. LESSONS
CREATE TABLE IF NOT EXISTS lessons (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  class_time TEXT,
  location_name TEXT,
  formatted_address TEXT,
  city TEXT,
  country TEXT,
  lat FLOAT8,
  lng FLOAT8,
  status TEXT DEFAULT 'pending' CHECK (status IN ('draft', 'pending', 'published', 'cancelled', 'expired')),
  price INTEGER DEFAULT 0,
  max_attendees INTEGER DEFAULT 0,
  host_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  image_url TEXT,
  level TEXT DEFAULT 'beginner',
  is_banner BOOLEAN DEFAULT false,
  priority INTEGER DEFAULT 0,
  likes_count INTEGER DEFAULT 0,
  tickets JSONB DEFAULT '[]',
  payment_method TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. REGISTRATIONS
CREATE TABLE IF NOT EXISTS registrations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  event_id UUID NOT NULL, 
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  registered_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. COMMUNITY
CREATE TABLE IF NOT EXISTS community_posts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  token_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('free', 'inquiry', 'review')),
  author_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS community_comments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  post_id UUID REFERENCES community_posts(id) ON DELETE CASCADE NOT NULL,
  author_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS event_comments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id UUID NOT NULL, 
  author_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS event_reviews (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id UUID NOT NULL, 
  author_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS event_photos (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id UUID NOT NULL, 
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL,
  caption TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 6. SETTINGS & OTHERS
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS promo_banners (
  id TEXT PRIMARY KEY,
  image_url TEXT NOT NULL,
  link_url TEXT DEFAULT '#',
  is_active BOOLEAN DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_ai_configs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  api_key TEXT NOT NULL,
  model TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, provider)
);

CREATE TABLE IF NOT EXISTS point_history (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  amount INTEGER NOT NULL,
  reason TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
